#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application("Advent of Code 2018");

// $app->add(new Aoc\One\OneCommand);
// $app->add(new Aoc\Two\TwoCommand);
$app->add(new Aoc\Five\FiveCommand);
$app->add(new Aoc\Seven\SevenCommand);
$app->add(new Aoc\Eight\EightCommand);

$app->run();